### PR TITLE
Jekyll Material Design

### PR DESCRIPTION
**Pull request by christoga**
Jekyll material design template

### CODE REVIEW

**Comment by christoga** [comment]
So,,
Jekyll is static page generator using ruby created by @mojombo and others

**Comment by christoga** [comment]
Folders Explanation :

**Comment by christoga** [comment]
_includes : 
  footer.html - Website footer
  head.html - HTML <head> tag
  header.html - Website header

**Comment by christoga** [comment]
_layouts :  
  default.html - Default layout
  page.html : Website index
  post.html : Your posts layout

**Comment by christoga** [comment]
_posts : This folder is where you put your post
The post written using markdown, and it has some option

Example : 
```markdown
---
layout: post
title: Hello World!
date: 2015-11-30
categories: lifestyle
author: Andre Christoga
---

**Hello world!**
<br>
I'm Christo,
From now on I will write post about :

* My Journey
* Tech Updates
* Tips & Tricks

<br>
The post will written in Indonesia or English,
Thank you for visiting my blog by the way!

```

**Comment by christoga** [comment]
css, img, js : Website source code

**Comment by christoga** [comment]
_config.yml : Website configuration

**Comment by christoga** [comment]
about.md : About page

**Comment by vickydasta** [comment]
:+1:

**Comment by christoga** [comment]
That's it bro

**Comment by christoga** [comment]
Simple, right?

**Comment by christoga** [comment]
Go write a hello world post! @vickydasta 
http://vickydasta.github.io/

**Pull request merged**
